---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-8.2
  - name: fedora-23

suites:
  - name: hekad
    run_list:
      - recipe[hekad]
      - recipe[setup]
