---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1
  - name: debian-8.1
  - name: fedora-21

suites:
  - name: hekad
    run_list:
      - recipe[hekad]
