---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-9.2
  - name: ubuntu-16.04
  - name: centos-7.4

suites:
  - name: hekad
    run_list:
      - recipe[hekad]
      - recipe[setup]
